# 🔍 Data Detective Challenge

Your mission, should you choose to accept it, is to investigate the dataset, solve data quality issues, and prepare it for machine learning.

**Section 1: Exploration**

---

1.1 Import pandas, seaborn

In [1]:
import seaborn as sns
import pandas as pd

1.2 Load the Titanic dataset from seaborn

In [2]:
df = sns.load_dataset("titanic")

1.3 Inspect the first 5 and last 5 rows of the dataset

In [3]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [4]:
df.tail()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
886,0,2,male,27.0,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.00,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True

1.4 Get the shape of the dataset

In [5]:
df.shape

(891, 15)

1.5 Detailed summary of the data

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

1.6 Show descriptive statistics of our data (Hint: mean, mode, max, min etc.)

In [ ]:
df.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

**Section 2: Preprocessing**

---

2.1 Check for any missing data (NaNs/nulls) and quantify the amount of missing data

In [ ]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

2.2 Handle the missing values using an appropriate method.

In [ ]:
df['age'] = df['age'].fillna(df['age'].median()) #numerical column

In [ ]:
#categorical columns
df['embarked'] = df['embarked'].fillna(df['embarked'].mode()[0])

df['embark_town'] = df['embark_town'].fillna(df['embark_town'].mode()[0])

In [ ]:
df = df.drop(columns=['deck'])

2.3 Check for duplicate rows and remove them if any exist.

In [ ]:
df.duplicated().sum()

np.int64(116)

In [ ]:
df = df.drop_duplicates()

2.4 Detect outliers using the IQR method.

In [ ]:
Q1 = df['age'].quantile(0.25)
Q3 = df['age'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[(df['age'] < lower) | (df['age'] > upper)]

print(outliers)

     survived  pclass     sex   age  sibsp  parch      fare embarked   class  \
33          0       2    male  66.0      0      0   10.5000        S  Second
54          0       1    male  65.0      0      1   61.9792        C   First
94          0       3    male  59.0      0      0    7.2500        S   Third
96          0       1    male  71.0      0      0   34.6542        C   First
116         0       3    male  70.5      0      0    7.7500        Q   Third
170         0       1    male  61.0      0      0   33.5000        S   First
232         0       2    male  59.0      0      0   13.5000        S  Second
252         0       1    male  62.0      0      0   26.5500        S   First
275         1       1  female  63.0      1      0   77.9583        S   First
280         0       3    male  65.0      0      0    7.7500        Q   Third
326         0       3    male  61.0      0      0    6.2375        S   Third
366         1       1  female  60.0      1      0   75.2500        C   First
438         0       1    male  64.0      1      4  263.0000        S   First
456         0       1    male  65.0      0      0   26.5500        S   First
483         1       3  female  63.0      0      0    9.5875        S   Third
493         0       1    male  71.0      0      0   49.5042        C   First
545         0       1    male  64.0      0      0   26.0000        S   First
570         1       2    male  62.0      0      0   10.5000        S  Second
587         1       1    male  60.0      1      1   79.2000        C   First
625         0       1    male  61.0      0      0   32.3208        S   First
630         1       1    male  80.0      0      0   30.0000        S   First
672         0       2    male  70.0      0      0   10.5000        S  Second
684         0       2    male  60.0      1      1   39.0000        S  Second
694         0       1    male  60.0      0      0   26.5500        S   First
745         0       1    male  70.0      1      1   71.0000        S   First
829         1       1  female  62.0      0      0   80.0000        S   First
851         0       3    male  74.0      0      0    7.7750        S   Third

       who  adult_male  embark_town alive  alone
33     man        True  Southampton    no   True
54     man        True    Cherbourg    no  False
94     man        True  Southampton    no   True
96     man        True    Cherbourg    no   True
116    man        True   Queenstown    no   True
170    man        True  Southampton    no   True
232    man        True  Southampton    no   True
252    man        True  Southampton    no   True
275  woman       False  Southampton   yes  False
280    man        True   Queenstown    no   True
326    man        True  Southampton    no   True
366  woman       False    Cherbourg   yes  False
438    man        True  Southampton    no  False
456    man        True  Southampton    no   True
483  woman       False  Southampton   yes   True
493    man        True    Cherbourg    no   True
545    man        True  Southampton    no   True
570    man        True  Southampton   yes   True
587    man        True    Cherbourg   yes  False
625    man        True  Southampton    no   True
630    man        True  Southampton   yes   True
672    man        True  Southampton    no   True
684    man        True  Southampton    no  False
694    man        True  Southampton    no   True
745    man        True  Southampton    no  False
829  woman       False  Southampton   yes   True
851    man        True  Southampton    no   True

In [ ]:
print(len(outliers))

2.5 Encode the categorical variables.

In [ ]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

df['sex'] = encoder.fit_transform(df['sex'])
df['embarked'] = encoder.fit_transform(df['embarked'])
df['class'] = encoder.fit_transform(df['class'])
df['who'] = encoder.fit_transform(df['who'])
df['adult_male'] = encoder.fit_transform(df['adult_male'])
df['alive'] = encoder.fit_transform(df['alive'])
df['alone'] = encoder.fit_transform(df['alone'])

2.5 Create a new feature called family_size

In [ ]:
df['family_size'] = df['sibsp'] + df['parch'] + 1

In [ ]:
df['is_child'] = (df['age'] < 18).astype(int)

2.6 Normalize the numerical features.

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

columns = ['age','fare','family_size']

df[columns] = scaler.fit_transform(df[columns])

2.7 Randomize the dataset.

In [ ]:
df = df.sample(frac=1, random_state=42).reset_index(drop=True)

2.8 Produce a correlation heatmap.

In [ ]:
corr = df.corr(numeric_only=True)

corr

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10,8))

sns.heatmap(corr,
            annot=True,
            cmap="coolwarm")

plt.show()

Save the cleaned dataset as a CSV file.

In [ ]:
df.to_csv("titanic_cleaned.csv", index=False)

💡Remember:
"A machine learning model is only as good as the data you feed it."
Great job preparing your data!